### ISSUE TITLE
customize keys

### ISSUE THREAD

**Issue by bjartek** [mrvaita/sqlrun.nvim#5]
Have you considered adding support for overriding keymap bindings?

**Comment by mrvaita** [comment]
Hello, thank you for your interest in my little plugin. As far as I know this functionality was enabled with [#3](https://github.com/mrvaita/sqlrun.nvim/pull/3).

For example you can simply add the following to your neovim configuration
```lua
vim.keymap.set('n', '<leader>l', ":lua require('sqlrun').execute_current_line()<CR>", {noremap = true})
vim.keymap.set('v', '<leader>q', ":lua require('sqlrun').execute_selection()<CR>", {noremap = true})
```
and replace `<leader>l` and `<leader>q` with your favorite key bindings.
I hope that helps.

**Comment by bjartek** [comment]
Thanks!
